# Generated by Django 4.2.5 on 2023-09-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchqueue",
            name="get_ready",
        ),
    ]
