# Generated by Django 4.2.5 on 2023-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_matchqueue_get_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchqueue",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
